# Generated by Django 3.1.2 on 2020-10-28 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('meta_desc', models.CharField(editable=False, max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=150, unique=True)),
                ('meta_desc', models.CharField(editable=False, max_length=144)),
                ('thumbnail', models.URLField()),
                ('is_active', models.BooleanField(default=1)),
                ('category', models.ManyToManyField(related_name='category', to='products.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productdetail', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_media', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_price', models.FloatField(blank=True, default=-1, null=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('variant', models.CharField(blank=True, default=-1, max_length=50)),
                ('variable', models.CharField(blank=True, default=-1, max_length=50)),
                ('thumbnail', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='products.product')),
            ],
        ),
    ]
